server:
  host: 0.0.0.0
  port: 8089
  request_timeout_s: 6000000
  instance_health_check_interval_s: 10.0
  instance_health_check_timeout_s: 10.0

scheduler:
  tie_breaker: random
  ewma_alpha: 0.2

policy:
  baseline:
    # 单卡下全局调度基本无意义，但这里保留你给的 round_robin 结构
    algorithm: round_robin

benchmark:
  # 单卡实验：只启用 worker0
  worker_ids: [worker0]
  worker_ready_timeout_s: 12000

  model: /data2/group_谈海生/mumura/models/Qwen-Image
  backend: vllm-omni
  task: t2i

  # 用 trace 生成“固定100条请求”
  dataset: trace
  dataset_path: /home/mumura/omni/vllm-omni/benchmarks/diffusion/scripts/global_instance_scheduler_v2/xhf_tmp/datasets/datasetX.trace.txt

  max_concurrency: 100000000
  warmup_requests: 8
  warmup_num_inference_steps: 1
  output_file: ./logs/global_scheduler_qwen_image_benchmark_metrics.json
  auto_stop: true

instances:
  - id: worker0
    endpoint: http://127.0.0.1:8001
    instance_type: qwen-image
    numa_node: 0
    backends: [vllm-omni, openai]
    launch:
      executable: vllm-omni
      model: /data2/group_谈海生/mumura/models/Qwen-Image
      args:
        - --omni
        - --diffusion-engine-max-concurrency
        - "100"
        - --instance-scheduler-policy
        - sjf
        - --ulysses-degree
        - "1"
        - --cfg-parallel-size
        - "1"
        - --vae-use-slicing
        - --vae-use-tiling
        - --num-weight-load-threads
        - "4"
      env:
        CUDA_VISIBLE_DEVICES: "0"
    stop:
      executable: pkill
      args:
        - -f
        - "vllm-omni serve /data2/group_谈海生/mumura/models/Qwen-Image --port {endpoint_port}"

